### ISSUE TITLE
!listsongs with argument not working for large playlists?

### ISSUE THREAD

**Issue by zeblau** [matthieugrieger/mumbledj#117]
Hi!

Was just trying the !listsongs command with a playlist containing 100+ songs (and the config is set to add unlimited songs per playlist):

!listsongs without argument should list all songs, the bot does not return anything.
!listsongs 10 lists the first 10 songs.
!listsongs 70 does not list anything.

!numsongs gives the correct total number of songs in the queue.

It seems to be at around 50~60 songs in the queue when the !listsongs command stops working as expected, the exact number where it stops working is not consistent accross playlists it seems.

After letting the queue play until there are <50 songs queued, then !listsongs without arguments lists all songs in the queue as expected.

Do others experience this too?

**Comment by matthieugrieger** [comment]
Yes, this is expected. What is happening is that the message that is assembled for the `!listsongs` command is too long for Mumble to display. When the message is too long, nothing is displayed.

The reason that it doesn't happen at a specific number of songs is that the generated string for each song is of variable length. For example, the title of one song is longer than another. Because of this you will hit the limit with a smaller number of songs if the song titles are longer in general.

I have yet to come up with a good solution for this issue, and this issue is why there is an argument for `!listsongs` to limit the number of songs listed.

Hopefully this answers your question!
