### ISSUE TITLE
[Request] Allow bot to type message every X seconds.

### ISSUE THREAD

**Issue by NonklyFriend** [matthieugrieger/mumbledj#132]
Hi, I currently have a mumble server that has a idle channel. Which moves people who've been idle for 1hour. Is the a way to programme the bot to type every 59mins, so it doesn't get moved to the AFK channel.

**Comment by matthieugrieger** [comment]
Since this is a fairly specific request, I don't think it would make sense to implement it for everyone. Feel free to fork this repository and implement it yourself though!

You could simply set up another goroutine that loops forever (similar to how the caching system works), and make it send a message every 59 minutes. Shouldn't be too difficult.
