### ISSUE TITLE
gopus function ends without return statement

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#25]
$ make
go get -u github.com/layeh/gumble/gumble
# github.com/layeh/gopus
gopus.go:32[/tmp/go-build747645988/github.com/layeh/gopus/_obj/gopus.cgo1.go:27]: function ends without a return statement
make: *** [mumbledj] Error 2

Am I missing something?

**Comment by matthieugrieger** [comment]
I can't reproduce this on my own machine. Are you sure you have `opus` and its development headers/libraries installed?

**Comment by hamilton5** [comment]
I've installed 4 packages for opus...  libopus0, libopusfile0, libopus-dev, and libopusfile-dev. Do you have a debug script? I cant tell what I'm missing, the /tmp file is gone after the make error.

This is on Debian 7 64bit

**Comment by matthieugrieger** [comment]
Hmm.. strange. I know that there are multiple people running MumbleDJ on Debian and they didn't seem to have this problem.

Unfortunately I don't have any sort of debug script. Usually the Makefile error messages are enough to figure out what the issue is.

[`cgo`](https://golang.org/cmd/cgo/) is listed as a dependency for `gopus`. Maybe you're missing that? I 'm not quite sure how you go about installing it as I've never had to manually do it.

**Comment by hamilton5** [comment]
I blindly ignored the fact go 1.3+ was required and I was trying to use one from june 2012 - issue resolved

**Comment by matthieugrieger** [comment]
Ah! That'll do it. Glad it's working now!
