### ISSUE TITLE
Build sometimes failed while fetching dependencies...

### ISSUE THREAD

**Issue by raz0rsdge** [matthieugrieger/mumbledj#38]
=> Fetching github.com/layeh/gumble/gumble_ffmpeg...
Warning: /home/raz0r/mumbledj/.vendor/src/github.com/layeh/gumble already exists; skipping!
Checking out "ed900e422315c00121362676dd51aa0506ee18c0"
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/layeh/gumble/info/refs

This error sometimes occurs when trying to build... I asume this is not a mumbledj failure.

**Comment by matthieugrieger** [comment]
Strange.. I've never had this happen to me. I'll take a look to see if I can find out what's going on, but I suspect that this isn't a MumbleDJ issue, like you said.

**Comment by matthieugrieger** [comment]
Yeah, looks like this is some sort of issue with your `git` setup. Here is a link with some possible solutions: https://help.github.com/articles/https-cloning-errors/.

If you can't get it working let me know. I'm going to close this issue since it is not related to MumbleDJ, but feel free to comment on here if you need help getting it working.

**Comment by raz0rsdge** [comment]
It only happens once in a while, if I go into make for a second round - then all runs through fine...
Sry for not clearing that out...

Maybe I have 'toasted' too much dependencies ;)
