### ISSUE TITLE
Text to speech 

### ISSUE THREAD

**Issue by Maximumpower** [matthieugrieger/mumbledj#41]
We have a different bot on our mumble along with your bot. the other bot has Text to speech. basically a robot voice for people without mics. Maybe you could incorporate this?

**Comment by matthieugrieger** [comment]
Do you mean having MumbleDJ say chat messages using text to speech? If so, it isn't possible unfortunately. I can't play both text-to-speech audio and YouTube audio at the same time.

**Comment by Maximumpower** [comment]
Most people who use it on my server don't use it while songs are playing because it's too hard to hear anyway. But something people like is when you turn the volume of the bot up the volume of text to speech goes up. So if someone is in game for example and can't hear text to speech they just turn it up. It is usually triggered by !tts message.

**Comment by matthieugrieger** [comment]
Unfortunately I don't think there's any way I could implement this in MumbleDJ. It would be great, but I don't think there is a simple way to play both audio from YouTube and audio from TTS at the same time.

Do you have access to the source for the TTS bot? If so, you could probably just make the TTS bot listen for `!volume` commands so that it changes its volume whenever the volume of MumbleDJ changes.
