### ISSUE TITLE
audio download failed, numsongs still 1 (does not skip to next song)

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#43]
I'm seeing a lot more 'audio download fails' lately, and on songs that have worked in the past.

If one of these songs is the first to get added it will not skip and need a !reset - you can !add but nothing is played, the song is not actually skipped

Also Ive been experimenting with multiple bots on different servers do you for see any problems with this?

**Comment by matthieugrieger** [comment]
Thanks for the report! It's something small that I overlooked.

**Comment by matthieugrieger** [comment]
@hamilton5: Forgot to answer your last question. If you are hosting multiple bots on one machine that are connecting to separate servers, it should work okay. Just make sure that your machine has enough resources to run them all at once, and also make sure that you put the `-insecure` flag in your commandline options so that you do not clobber `cert.lock`.
