### ISSUE TITLE
not sound

### ISSUE THREAD

**Issue by THEDARKK** [matthieugrieger/mumbledj#7]
Hello, Happy new year, my bot runs but not sound.
I have a virtual machine that has no sound card, it is because her?
Codec : CELT 0.7.0
thank you

**Comment by THEDARKK** [comment]
Hello, I tested on another mumble is work.
But we can not make it work on a CELT mumble?

thank you

**Comment by matthieugrieger** [comment]
CELT compatibility would require an update to [`gumble`](https://github.com/layeh/gumble), but I doubt it would be implemented since CELT is now obsolete.

Is there a reason you need to use CELT? If you are using a Mumble server provider try asking them to switch your server to Opus if they do not give you the option to change it yourself.
