### ISSUE TITLE
After MAKE, MAKE install puts error

### ISSUE THREAD

**Issue by satinez** [matthieugrieger/mumbledj#85]
Hello again :)

i get this error, installed whole server new, and still getting this error msg.

Im using GOLANG 1.5

root@debian:~/mumbledj# make install
mkdir -p ~/.mumbledj/config
mkdir -p ~/.mumbledj/songs
if [ -a ~/.mumbledj/config/mumbledj.gcfg ]; then mv ~/.mumbledj/config/mumbledj.gcfg ~/.mumbledj/config/mumbledj_backup.gcfg; fi;
/bin/sh: 1: [: -a: unexpected operator
cp -u config.gcfg ~/.mumbledj/config/mumbledj.gcfg
if [ -d ~/bin ]; then cp -f mumbledj* ~/bin/mumbledj; else sudo cp -f mumbledj* /usr/local/bin/mumbledj; fi;

I know there is similar IssueThread closed, but no solution?
greet;s satinez

**Comment by matthieugrieger** [comment]
The reason why there is no solution is because I'm pretty sure you can just ignore this error (I'm assuming you're talking about the unexpected operator error).

Check `/usr/local/bin` to see if there is a `mumbledj` executable there. Or check `~/bin` for the same executable if that folder exists. There should be a `mumbledj` executable that has been successfully created.

I know that this "error" message is a bit confusing. I'm hoping to clean up the installation process fairly soon.

Let me know if your installation actually went through or not.

**Comment by satinez** [comment]
Hello again :) Installation seems to work. Bot is connecting fine.

**Comment by matthieugrieger** [comment]
Awesome! Let me know if anything else pops up.
