### ISSUE TITLE
request: Installation guide for Linux dummies

### ISSUE THREAD

**Issue by 14422** [matthieugrieger/mumbledj#93]
For people who hardly know Linux (me) it would be nice to have detailed installation instructions with no assumptions that the user has studied black magic.

(Black magic = development headers? "make sure that ~/bin exists and is added to your $PATH"? "Clone the MumbleDJ repository" in Linux? and so on..)

Murmur alone is fairly easy to setup and there's detailed instructions for even fine tuning the .ini file so it would be nice to have this DJ to be as easily available.

**Comment by matthieugrieger** [comment]
I'm currently working on a refactor of the bot, and I am hoping to make the installation process more automated via Docker or something similar. This should hopefully eliminate most of the setup steps. No idea when this refactor will be done, however, since I am currently finishing up my last year of university.

In the meantime, I am happy to explain anything that doesn't make sense.

* Development headers: On most distros you can just install these via the package manager (`apt-get` on Ubuntu, `pacman` on Arch Linux, `dnf` on Fedora, etc.). I believe you only need the `opus` development headers for MumbleDJ, which are likely either called `libopus-dev` or `opus-devel`.
* Make sure that ~/bin exists and is added to your $PATH: This step actually is optional. Essentially all this is saying is that you can create a folder called `bin` in your home directory (`/home/username`) and the MumbleDJ installer will detect that and install the binary to that location instead of a location that requires root privileges. `$PATH` is an environment variable that tells the system which directories should be searched for binaries whenever a command on the terminal is issued. Again, you can just skip this step if you don't care about root privileges during installation.
* Clone the MumbleDJ repository: This part is fairly simple. Just install `git` on your system and issue the following command: `git clone https://github.com/matthieugrieger/mumbledj.git`. This will create a folder that contains the MumbleDJ source files.

Hopefully this helps. Let me know if I can clear anything else up!

**Comment by raz0rsdge** [comment]
@14422 I disagree by the point that the dev has to explain the linux command line basics, also I think it's not his part to deliver git use instructions, the possibility of a git install should be enough as explanation. 

The https://github.com/matthieugrieger/mumbledj/blob/master/README.md#installation file is fine, needs, if possible, some finetuning imho.

**Comment by 14422** [comment]
@raz0rsdge That's why this is just a request. I'm not demanding anything. I do not see your point of why it should remain cryptic for dummies as it requires just clear phrases of what needs to be done to get it installed. Just like with the case of installing Murmur. Should it be available only for those whole have lived with linux?

Me and my relatives are mostly using linux just for server side stuff (with raspberry pi) and for nothing else. I don't feel like I should learn everything about linux just to get this nicely done bot working. Even if I'm quite skillful with Windows OS, I find these instructions quite demanding to be instructions.

**Comment by matthieugrieger** [comment]
@14422: Did the explanations I gave earlier help? Is there anything else I can attempt to clear up?

**Comment by matthieugrieger** [comment]
Also, @raz0rsdge, what fine-tuning would you recommend for the README?

**Comment by raz0rsdge** [comment]
From my pov, I'd only change cosmetics... First part INSTALLATION with dependencies, then USAGE of the successfully installed mumbledj and stuff...

but thats a very own view, also English isn't my native language, so things may be different.

**Comment by matthieugrieger** [comment]
Cool, thanks. Those were some changes that I was thinking about making anyway.

**Comment by 14422** [comment]
@matthieugrieger Well here's my progress with the instructions so far:

Youtube API keys part ok.
Skipped soundcloud API keys, don't need.

1) GO
- Had to google how to install GO in terminal
- Did this:
sudo apt-get install -y mercurial gcc libc6-dev
hg clone -u default https://code.google.com/p/go $HOME/go
cd $HOME/go/src
./all.bash

- From ~8 pages of text about configuration, was I expected to find just this?:
export PATH=$PATH:$HOME/go/bin

2) ffmpeg, mercurial, opus, opus' development headers and openal

- No idea how to check if any of these are already installed.
- No idea how to check distributions repo for a package name. Don't even know what distributions repo is.
- Had to google how to install every single of them in terminal.
- Installed all of them just to be sure.

ffmpeg
- Did this:
cd /usr/src
git clone git://source.ffmpeg.org/ffmpeg.git
cd ffmpeg
sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
make
sudo make install

mercurial
- Did this:
sudo apt-get install mercuria
- Noticed afterwards that GO installation instructions actually installed mercurial already? Except with "gcc libc6-dev" which I have no idea of what it does.

Next up, opus, opus' development headers and openal.

With the amount of time spent already to struggle through this, would I recommend it for other windows users? Nope. At this point I already feel like I should have just started making my own bot, except for windows. However I'll go through the rest of the steps when I have more time. That ffmpeg part alone took like 4 hours for my raspberry to make/install.

**Comment by matthieugrieger** [comment]
Yep, learning Linux is a bit of a learning curve. 

From your comments, am I correct in assuming you're running Raspbian? If so, try using the package names I listed above to install the opus development headers with `apt-get`.

It would be great to explain every step in great detail, but then the README would be very long and cumbersome to navigate for more experienced users.

**Comment by 14422** [comment]
I still 3), skipped 4), 5) (thanks for the help with this one) but with 6) when trying to "make" in the mumbleDJ directoy I get "make: go: command not found. Makefile4: recipe for target 'mumbledj' failed" and so on. I guess my GO installation didn't go through properly?

I guess I'll leave it at that point if there's no sense in making the README long enough for dummies. Thanks for the support though. May to code be with you o/

**Comment by matthieugrieger** [comment]
If you haven't already you might want to read through the following page:

https://golang.org/doc/install

You probably installed Go correctly but the system just doesn't know where to look for it.

**Comment by matthieugrieger** [comment]
Closing this issue as the installation guide is detailed enough already in my opinion. The guide assumes that some knowledge of Linux usage is already present.
